# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZPop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='zlogin',
        ),
    ]
