# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZPop', '0002_auto_20180102_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='zlogin',
            name='password',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
